spring:
  cloud:
    consul:
      discovery:
        register: false
      host: 172.31.224.198
      port: 8500
    service-registry:
      auto-registration:
        enabled: false
server:
  port: 9090