// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;
using _Microsoft = global::Microsoft;

#pragma warning disable 1591

namespace IceCompactId
{
}

namespace Demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public enum Color
    {
        red,
        green,
        blue
    }

    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
#if !SILVERLIGHT
    [_System.Serializable]
#endif
    public partial class Structure : _System.ICloneable
    {
        #region Slice data members

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public string name;

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public Demo.Color value;

        #endregion

        #region Constructors

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public Structure()
        {
            name = "";
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public Structure(string name, Demo.Color value)
        {
            this.name = name;
            this.value = value;
        }

        #endregion

        #region ICloneable members

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public object Clone()
        {
            return MemberwiseClone();
        }

        #endregion

        #region Object members

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public override int GetHashCode()
        {
            int h__ = 5381;
            IceInternal.HashUtil.hashAdd(ref h__, "::Demo::Structure");
            IceInternal.HashUtil.hashAdd(ref h__, name);
            IceInternal.HashUtil.hashAdd(ref h__, value);
            return h__;
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public override bool Equals(object other__)
        {
            if(object.ReferenceEquals(this, other__))
            {
                return true;
            }
            if(other__ == null)
            {
                return false;
            }
            if(GetType() != other__.GetType())
            {
                return false;
            }
            Structure o__ = (Structure)other__;
            if(name == null)
            {
                if(o__.name != null)
                {
                    return false;
                }
            }
            else
            {
                if(!name.Equals(o__.name))
                {
                    return false;
                }
            }
            if(!value.Equals(o__.value))
            {
                return false;
            }
            return true;
        }

        #endregion

        #region Comparison members

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public static bool operator==(Structure lhs__, Structure rhs__)
        {
            return Equals(lhs__, rhs__);
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public static bool operator!=(Structure lhs__, Structure rhs__)
        {
            return !Equals(lhs__, rhs__);
        }

        #endregion

        #region Marshalling support

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public void write__(IceInternal.BasicStream os__)
        {
            os__.writeString(name);
            os__.writeEnum((int)value, 2);
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public void read__(IceInternal.BasicStream is__)
        {
            name = is__.readString();
            value = (Demo.Color)is__.readEnum(2);
        }
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public static void write__(IceInternal.BasicStream os__, Structure v__)
        {
            if(v__ == null)
            {
                nullMarshalValue__.write__(os__);
            }
            else
            {
                v__.write__(os__);
            }
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
        public static Structure read__(IceInternal.BasicStream is__, Structure v__)
        {
            if(v__ == null)
            {
                v__ = new Structure();
            }
            v__.read__(is__);
            return v__;
        }
        
        private static readonly Structure nullMarshalValue__ = new Structure();

        #endregion
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
    public partial interface Hello : Ice.Object, HelloOperations_, HelloOperationsNC_
    {
    }
}

namespace Demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public delegate void Callback_Hello_sayHello();

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public delegate void Callback_Hello_shutdown();

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public delegate void Callback_Hello_get(Demo.Structure ret__);
}

namespace Demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public interface HelloPrx : Ice.ObjectPrx
    {
        void sayHello(int delay);
        void sayHello(int delay, _System.Collections.Generic.Dictionary<string, string> context__);

        Ice.AsyncResult<Demo.Callback_Hello_sayHello> begin_sayHello(int delay);
        Ice.AsyncResult<Demo.Callback_Hello_sayHello> begin_sayHello(int delay, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_sayHello(int delay, Ice.AsyncCallback cb__, object cookie__);
        Ice.AsyncResult begin_sayHello(int delay, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        void end_sayHello(Ice.AsyncResult r__);

        void shutdown();
        void shutdown(_System.Collections.Generic.Dictionary<string, string> context__);

        Ice.AsyncResult<Demo.Callback_Hello_shutdown> begin_shutdown();
        Ice.AsyncResult<Demo.Callback_Hello_shutdown> begin_shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_shutdown(Ice.AsyncCallback cb__, object cookie__);
        Ice.AsyncResult begin_shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        void end_shutdown(Ice.AsyncResult r__);

        Demo.Structure get(string name);
        Demo.Structure get(string name, _System.Collections.Generic.Dictionary<string, string> context__);

        Ice.AsyncResult<Demo.Callback_Hello_get> begin_get(string name);
        Ice.AsyncResult<Demo.Callback_Hello_get> begin_get(string name, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_get(string name, Ice.AsyncCallback cb__, object cookie__);
        Ice.AsyncResult begin_get(string name, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        Demo.Structure end_get(Ice.AsyncResult r__);
    }
}

namespace Demo
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public interface HelloOperations_
    {
        void sayHello(int delay, Ice.Current current__);

        void shutdown(Ice.Current current__);

        Demo.Structure get(string name, Ice.Current current__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public interface HelloOperationsNC_
    {
        void sayHello(int delay);

        void shutdown();

        Demo.Structure get(string name);
    }
}

namespace Demo
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public sealed class HelloPrxHelper : Ice.ObjectPrxHelperBase, HelloPrx
    {
        #region Synchronous operations

        public Demo.Structure get(string name)
        {
            return this.get(name, null, false);
        }

        public Demo.Structure get(string name, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            return this.get(name, context__, true);
        }

        private Demo.Structure get(string name, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            checkTwowayOnly__(__get_name);
            return end_get(begin_get(name, context__, explicitCtx__, true, null, null));
        }

        public void sayHello(int delay)
        {
            this.sayHello(delay, null, false);
        }

        public void sayHello(int delay, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            this.sayHello(delay, context__, true);
        }

        private void sayHello(int delay, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            end_sayHello(begin_sayHello(delay, context__, explicitCtx__, true, null, null));
        }

        public void shutdown()
        {
            this.shutdown(null, false);
        }

        public void shutdown(_System.Collections.Generic.Dictionary<string, string> context__)
        {
            this.shutdown(context__, true);
        }

        private void shutdown(_System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            end_shutdown(begin_shutdown(context__, explicitCtx__, true, null, null));
        }

        #endregion

        #region Asynchronous operations

        public Ice.AsyncResult<Demo.Callback_Hello_get> begin_get(string name)
        {
            return begin_get(name, null, false, false, null, null);
        }

        public Ice.AsyncResult<Demo.Callback_Hello_get> begin_get(string name, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_get(name, ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_get(string name, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_get(name, null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_get(string name, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_get(name, ctx__, true, false, cb__, cookie__);
        }

        private const string __get_name = "get";

        public Demo.Structure end_get(Ice.AsyncResult r__)
        {
            IceInternal.OutgoingAsync outAsync__ = IceInternal.OutgoingAsync.check(r__, this, __get_name);
            try
            {
                if(!outAsync__.wait())
                {
                    try
                    {
                        outAsync__.throwUserException();
                    }
                    catch(Ice.UserException ex__)
                    {
                        throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                    }
                }
                Demo.Structure ret__;
                IceInternal.BasicStream is__ = outAsync__.startReadParams();
                ret__ = null;
                ret__ = Demo.Structure.read__(is__, ret__);
                outAsync__.endReadParams();
                return ret__;
            }
            finally
            {
                outAsync__.cacheMessageBuffers();
            }
        }

        private Ice.AsyncResult<Demo.Callback_Hello_get> begin_get(string name, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            checkAsyncTwowayOnly__(__get_name);
            IceInternal.TwowayOutgoingAsync<Demo.Callback_Hello_get> result__ =  getTwowayOutgoingAsync<Demo.Callback_Hello_get>(__get_name, get_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__get_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                os__.writeString(name);
                result__.endWriteParams();
                result__.invoke();
            }
            catch(Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void get_completed__(Ice.AsyncResult r__, Demo.Callback_Hello_get cb__, Ice.ExceptionCallback excb__)
        {
            Demo.Structure ret__;
            try
            {
                ret__ = end_get(r__);
            }
            catch(Ice.Exception ex__)
            {
                if(excb__ != null)
                {
                    excb__(ex__);
                }
                return;
            }
            if(cb__ != null)
            {
                cb__(ret__);
            }
        }

        public Ice.AsyncResult<Demo.Callback_Hello_sayHello> begin_sayHello(int delay)
        {
            return begin_sayHello(delay, null, false, false, null, null);
        }

        public Ice.AsyncResult<Demo.Callback_Hello_sayHello> begin_sayHello(int delay, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_sayHello(delay, ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_sayHello(int delay, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_sayHello(delay, null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_sayHello(int delay, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_sayHello(delay, ctx__, true, false, cb__, cookie__);
        }

        private const string __sayHello_name = "sayHello";

        public void end_sayHello(Ice.AsyncResult r__)
        {
            end__(r__, __sayHello_name);
        }

        private Ice.AsyncResult<Demo.Callback_Hello_sayHello> begin_sayHello(int delay, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            IceInternal.OnewayOutgoingAsync<Demo.Callback_Hello_sayHello> result__ = getOnewayOutgoingAsync<Demo.Callback_Hello_sayHello>(__sayHello_name, sayHello_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__sayHello_name, Ice.OperationMode.Idempotent, ctx__, explicitContext__, synchronous__);
                IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                os__.writeInt(delay);
                result__.endWriteParams();
                result__.invoke();
            }
            catch(Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void sayHello_completed__(Demo.Callback_Hello_sayHello cb__)
        {
            if(cb__ != null)
            {
                cb__();
            }
        }

        public Ice.AsyncResult<Demo.Callback_Hello_shutdown> begin_shutdown()
        {
            return begin_shutdown(null, false, false, null, null);
        }

        public Ice.AsyncResult<Demo.Callback_Hello_shutdown> begin_shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_shutdown(ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_shutdown(Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_shutdown(null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_shutdown(ctx__, true, false, cb__, cookie__);
        }

        private const string __shutdown_name = "shutdown";

        public void end_shutdown(Ice.AsyncResult r__)
        {
            end__(r__, __shutdown_name);
        }

        private Ice.AsyncResult<Demo.Callback_Hello_shutdown> begin_shutdown(_System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            IceInternal.OnewayOutgoingAsync<Demo.Callback_Hello_shutdown> result__ = getOnewayOutgoingAsync<Demo.Callback_Hello_shutdown>(__shutdown_name, shutdown_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__shutdown_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                result__.writeEmptyParams();
                result__.invoke();
            }
            catch(Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void shutdown_completed__(Demo.Callback_Hello_shutdown cb__)
        {
            if(cb__ != null)
            {
                cb__();
            }
        }

        #endregion

        #region Checked and unchecked cast operations

        public static HelloPrx checkedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            HelloPrx r = b as HelloPrx;
            if((r == null) && b.ice_isA(ice_staticId()))
            {
                HelloPrxHelper h = new HelloPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static HelloPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            HelloPrx r = b as HelloPrx;
            if((r == null) && b.ice_isA(ice_staticId(), ctx))
            {
                HelloPrxHelper h = new HelloPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static HelloPrx checkedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId()))
                {
                    HelloPrxHelper h = new HelloPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static HelloPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId(), ctx))
                {
                    HelloPrxHelper h = new HelloPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static HelloPrx uncheckedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            HelloPrx r = b as HelloPrx;
            if(r == null)
            {
                HelloPrxHelper h = new HelloPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static HelloPrx uncheckedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            HelloPrxHelper h = new HelloPrxHelper();
            h.copyFrom__(bb);
            return h;
        }

        public static readonly string[] ids__ =
        {
            "::Demo::Hello",
            "::Ice::Object"
        };

        public static string ice_staticId()
        {
            return ids__[0];
        }

        #endregion

        #region Marshaling support

        public static void write__(IceInternal.BasicStream os__, HelloPrx v__)
        {
            os__.writeProxy(v__);
        }

        public static HelloPrx read__(IceInternal.BasicStream is__)
        {
            Ice.ObjectPrx proxy = is__.readProxy();
            if(proxy != null)
            {
                HelloPrxHelper result = new HelloPrxHelper();
                result.copyFrom__(proxy);
                return result;
            }
            return null;
        }

        #endregion
    }
}

namespace Demo
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public abstract class HelloDisp_ : Ice.ObjectImpl, Hello
    {
        #region Slice operations

        public void sayHello(int delay)
        {
            sayHello(delay, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract void sayHello(int delay, Ice.Current current__);

        public void shutdown()
        {
            shutdown(Ice.ObjectImpl.defaultCurrent);
        }

        public abstract void shutdown(Ice.Current current__);

        public Demo.Structure get(string name)
        {
            return get(name, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract Demo.Structure get(string name, Ice.Current current__);

        #endregion

        #region Slice type-related members

        public static new readonly string[] ids__ = 
        {
            "::Demo::Hello",
            "::Ice::Object"
        };

        public override bool ice_isA(string s)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override bool ice_isA(string s, Ice.Current current__)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override string[] ice_ids()
        {
            return ids__;
        }

        public override string[] ice_ids(Ice.Current current__)
        {
            return ids__;
        }

        public override string ice_id()
        {
            return ids__[0];
        }

        public override string ice_id(Ice.Current current__)
        {
            return ids__[0];
        }

        public static new string ice_staticId()
        {
            return ids__[0];
        }

        #endregion

        #region Operation dispatch

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus sayHello___(Hello obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Idempotent, current__.mode);
            IceInternal.BasicStream is__ = inS__.startReadParams();
            int delay;
            delay = is__.readInt();
            inS__.endReadParams();
            obj__.sayHello(delay, current__);
            inS__.writeEmptyParams__();
            return Ice.DispatchStatus.DispatchOK;
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus shutdown___(Hello obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            inS__.readEmptyParams();
            obj__.shutdown(current__);
            inS__.writeEmptyParams__();
            return Ice.DispatchStatus.DispatchOK;
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus get___(Hello obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            IceInternal.BasicStream is__ = inS__.startReadParams();
            string name;
            name = is__.readString();
            inS__.endReadParams();
            Demo.Structure ret__ = obj__.get(name, current__);
            IceInternal.BasicStream os__ = inS__.startWriteParams__(Ice.FormatType.DefaultFormat);
            Demo.Structure.write__(os__, ret__);
            inS__.endWriteParams__(true);
            return Ice.DispatchStatus.DispatchOK;
        }

        private static string[] all__ =
        {
            "get",
            "ice_id",
            "ice_ids",
            "ice_isA",
            "ice_ping",
            "sayHello",
            "shutdown"
        };

        public override Ice.DispatchStatus dispatch__(IceInternal.Incoming inS__, Ice.Current current__)
        {
            int pos = _System.Array.BinarySearch(all__, current__.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
            if(pos < 0)
            {
                throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
            }

            switch(pos)
            {
                case 0:
                {
                    return get___(this, inS__, current__);
                }
                case 1:
                {
                    return Ice.ObjectImpl.ice_id___(this, inS__, current__);
                }
                case 2:
                {
                    return Ice.ObjectImpl.ice_ids___(this, inS__, current__);
                }
                case 3:
                {
                    return Ice.ObjectImpl.ice_isA___(this, inS__, current__);
                }
                case 4:
                {
                    return Ice.ObjectImpl.ice_ping___(this, inS__, current__);
                }
                case 5:
                {
                    return sayHello___(this, inS__, current__);
                }
                case 6:
                {
                    return shutdown___(this, inS__, current__);
                }
            }

            _System.Diagnostics.Debug.Assert(false);
            throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
        }

        #endregion

        #region Marshaling support

        protected override void writeImpl__(IceInternal.BasicStream os__)
        {
            os__.startWriteSlice(ice_staticId(), -1, true);
            os__.endWriteSlice();
        }

        protected override void readImpl__(IceInternal.BasicStream is__)
        {
            is__.startReadSlice();
            is__.endReadSlice();
        }

        #endregion
    }
}
